project:
  type: website

website:
  title: "Diana-Gao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



